apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: it-infra@coremaker.io
    privateKeySecretRef:
      name: letsencrypt
    dns01:
      providers:
        - name: clouddns
          clouddns:
            serviceAccountSecretRef:
              name: cert-manager-secrets
              key: cert-manager-service.private-key.json
            project: {{ .Values.clouddns.projectId }}
